version: '3.9'

services:
  memeai-app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    volumes:
      - ../:/app
    working_dir: /app
    ports:
      - "5000:5000"
    command: python run.py
